name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create SBOM
        uses: docker/scout-action@v1
        with:
          command: sbom
          format: spdx
          image: fs:///${{ github.workspace }}
          output: ${{ github.workspace }}/matomo.spdx.json
          dockerhub-user: laurentgoderre689
          dockerhub-password: ${{ secrets.DOCKER_SCOUT_PAT }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
            name: sbom
            path: |
                matomo.spdx.json